name: Test project
on: push
jobs:
  testing_code:
    continue-on-error: true
    strategy:
      matrix:
        node: [14, 16, 18, 20]
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }} test environment
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run all tests
        run: npm test
        